print("Name: Michael Angelo P. Mosquito")
print("Birthday: June 8, 2005")
print("Gender: Male")
print("Email: michaelmosquito147@gmail.com")

print("Wassup my nigg")
print("Hello Kel! -Gerald")
print("This is my dedication from - simone")
print("ulol ka kel")
print("this is a new message for ivan")
print("ivan pogi talaga")